# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'
    
    - name: Build and test (MacOS)
      run: |
        set -x
        xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        
    - name: Build and test (iOS)
      run: |
        set -x
        xcodebuild clean build test -workspace EssentialApp.workspace -scheme "CI_iOS" -destination "platform=iOS Simulator,name=iPhone 15 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
